version: '3.8'

services:
  backend:
    image: lakshjain1/docker_assignment-backend:latest
    container_name: flask_backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    image: lakshjain1/docker_assignment-frontend:latest
    container_name: node_frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
